apiVersion: v2
appVersion: 11.1.00
dependencies:
- condition: hazelcast.enabled
  name: hazelcast
  repository: https://hazelcast-charts.s3.amazonaws.com/
  version: 5.8.14
- condition: influxdb.enabled
  name: influxdb
  repository: https://helm.influxdata.com/
  version: 4.12.0
- condition: grafana.enabled
  name: grafana
  repository: https://charts.bitnami.com/bitnami
  version: 9.5.2
- condition: database.create
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 9.14.2
- condition: config.redis.subChart.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.2.1
description: This Helm Chart deploys the Layer7 Gateway in Kubernetes.
home: https://github.com/CAAPIM/apim-charts
maintainers:
- name: Gazza7205
name: gateway
sources:
- https://github.com/CAAPIM/apim-charts
type: application
version: 3.0.27
