apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-06-08T04:51:51Z"
  generation: 1
  labels:
    app: yang
  name: yang
  namespace: default
  resourceVersion: "287938"
  uid: 874a4218-a550-433a-ac7c-13c21f3f749a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: yang
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yang
    spec:
      containers:
      - image: nginx:1.25.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
